# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout jp24u repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: sudo apt install graphicsmagick
      - run: wget https://jack.lib.unc.edu/packages/rhel7/repoview/kakadu.html/kakadu-8.3.0.02066L-4.el7_9.unc.x86_64.rpm
      - run: sudo apt install alien
      - run: sudo alien package.rpm
      - run: sudo apt install ./kakadu-8.3.0.02066L-4.el7_9.unc.x86_64.deb

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build jp24u with Maven
        run: mvn -B -U clean install